### ISSUE TITLE
Problem building/using Rocoto against Ruby v2.X under SLES12

### ISSUE THREAD

**Issue by texas-swift** [christopherwharrop/rocoto#1]
SLES 12 provides Ruby at a base level of v2.1.  Can Rocoto be built against Ruby v2.X?  Or does it require Ruby v1.8?

When running ./INSTALL from rocoto, I see messages like this:

compiling system_timer_native.c
In file included from system_timer_native.c:8:0:
/usr/include/ruby-2.1.0/ruby/backward/rubysig.h:14:2: warning: #warning rubysig.h is obsolete [-Wcpp]
 #warning rubysig.h is obsolete
  ^
system_timer_native.c: In function â:
system_timer_native.c:43:22: error: storage size of â isnât known
     struct itimerval timer_interval;
                      ^

**Comment by christopherwharrop** [comment]
The current version of Rocoto requires version 1.8.7 of Ruby.  Updating Rocoto to work with Ruby 2.x is under consideration, but there are no definitive plans yet.

**Comment by texas-swift** [comment]
Hello Christopher,

Thanks for the confirmation of Ruby 2.x not being supported yet.

Regards,
Spencer

**Comment by christopherwharrop** [comment]
FYI, I have made some first steps toward compatibility with Ruby > 1.8.  Initial results look encouraging, but more testing is needed.

**Comment by texas-swift** [comment]
Hello Christopher.

Thank you for the update.
I did manage to get Ruby v1.8 working under SLES12 recently.  And was able to complete a customer benchmark requiring rocoto.  However, if we complete a sale there, my preference would be to deliver an installation against the default SLES12 Ruby v2 installation.

Please continue to keep me updated.
Or is there an announcement list I can subscribe to?

Thank you again,
Spencer

## 

Spencer Swift
Sr. Applications Engineer

Texas Region
(214) 769-0672 cell
(509) 275-5451 fax
swift@sgi.com
spencerswift@skype

[cid:image001.png@01D2352C.3273D1D0]
accelerating results ™

900 North McCarthy Blvd.
Milpitas, CA 95035
www.sgi.com http://www.sgi.com

From: "vfrspencer@sbcglobal.net" vfrspencer@sbcglobal.net
Reply-To: christopherwharrop/rocoto reply@reply.github.com
Date: Wednesday, November 2, 2016 at 4:16 PM
To: christopherwharrop/rocoto rocoto@noreply.github.com
Cc: texas-swift vfrspencer@sbcglobal.net, Author author@noreply.github.com
Subject: Re: [christopherwharrop/rocoto] Problem building/using Rocoto against Ruby v2.X under SLES12 (#1)
Resent-From: Spencer Swift vfrspencer@sbcglobal.net
Resent-To: Spencer Swift swift@sgi.com
Resent-Date: Wednesday, November 2, 2016 at 5:11 PM

FYI, I have made some first steps toward compatibility with Ruby > 1.8. Initial results look encouraging, but more testing is needed.

**Comment by christopherwharrop** [comment]
Hi Spencer,

You can follow the issue thread on GitHub to keep up to date.  However,  I may have good news for you already.  After a couple additional adjustments and tests, I believe I have a version that works for all versions of ruby >= 1.8.

If you would like to test, please check out the issue_1 branch from GitHub and use ./INSTALL to build it for your version of Ruby.  It should build and function correctly.  Let me know your results.  Unless I hear of problems from user testing, I will merge this onto the master branch and it will be included with the next Rocoto release, 1.2.3.

**Comment by christopherwharrop** [comment]
I have merged the issue_1 branch onto the master and deleted issue_1.  If you would like to test compatibility, please clone the master.  The next release will include compatibility with Ruby > 1.8.  To be notified, you can "watch" this repository via GitHub interface.
