### ISSUE TITLE
running error "Error: Expecting an element cores, got nothing at ..."

### ISSUE THREAD

**Issue by natalie-perlin** [christopherwharrop/rocoto#101]
Building a rocoto XML workflow file for the platform that needs both "cluster" and "partition" to be specified in the batch script.  When "cluster" is added to the XML file, 
  ```
    <cluster>${CLUSTER}</cluster>
    <partition>${PARTITION}</partition>
```
      
following errors are generated (followed by filename of the rocoto_workflow.xml and line number):

```
rocoto_workflow.xml :: Error: Expecting an element cores, got nothing at ...
rocoto_workflow.xml :: Error: Invalid sequence in interleave at ... 
rocoto_workflow.xml ::  Error: Element task failed to validate content at ...
rocoto_workflow.xml ::  Error: Invalid sequence in interleave at ...
```

Is <cluster> not considered a valid entry for batch jobs in rocoto? Could this be added? I notice the "partition" appears to configured exclusively in relaxng.c. Is it the way to use similar approach for "cluster" entry?

**Comment by christopherwharrop** [comment]
@natalie-perlin - The `-M` or `--clusters` option is not supported in a generic way, so you'll have to use the `<native>` tag for it.  The dedicated generic tags are used for universal options that easily translate to many different batch systems.  The XML validation error that RelaxNG produces is confusing, assuming you do actually have the required `<cores>` tag in the XML.

**Comment by natalie-perlin** [comment]
Thank you, @christopherwharrop - 
  yes, <native> is indeed a way that helps to submit clusters specifications, it did work out!
