### ISSUE TITLE
inconsistent arguments/behavior between rocoto boot, stat, check, run, complete, and rewind.

### ISSUE THREAD

**Issue by samtrahan** [christopherwharrop/rocoto#17]
The rocotoboot, rocotostat, and rocotocomplete programs take these arguments:
  -c cycle or cycle llist
  -t task list
  -m metatask list
If multiple -c, -t, or -m are given, the last is used.  There is no error message to reflect this.

The rocotorewind program takes these arguments:
  -c one cycle
  -t one task
  -a     (no arguments; selects all tasks)
Multiple -c or -t will append the arguments.

This does not follow the Principle of Least Surprise at all, and the lack of certain capabilities is causing problems for some users, especially the lack of task lists or cycle ranges in rocotorewind, and the lack of a "-a" option in rocotocomplete.

The arguments should work the same way for all programs, and should have a superset of the capabilities.  Specifically,
  -c cycle or cycle llist
  -t task list
  -m metatask list
  -a      (no arguments; selects all tasks)
Multiple -c, -t, and -m should append, not replace.

-t :final should select all tasks with the "final=T" set.
-t `@name` should tasks for in cycledefs "name"
-t /regex/ should do a regex search on the task names.
-c `@name` should select all of cycledef "name"

Specifying -a to rocotorewind should mark the cycle as invalid (unstarted).
Specifying -a to rocotoboot should result in a big, angry, warning, with an "are you sure" message.
Specifying -a to rocotocomplete should mark the cycle as done, as of the time rocotocomplete was run.
The default for rocotorun should be "all cycles and all tasks."
When rocotorun is given a subset of the tasks and cycles, it should only submit jobs for those tasks and cycles.

**Comment by samtrahan** [comment]
This overlaps with issues #15 and #19.  Correcting this will correct both.

**Comment by samtrahan** [comment]
Current branch fixes rocotorun, rocotocomplete, rocotorewind, and rocotoboot.  I am now working on rocotostat and rocotocheck.

The -c option cannot select cycledefs (`-c @name`) yet, but the -t option can.  I want to get rocotostat working with the other options first, because its cycle selection logic is totally different (it asks the dbServer for cycles).

**Comment by samtrahan** [comment]
Chris,

You asked how I am handling booting of tasks in drained or expired cycles.  The purpose of rocotoboot is to force Rocoto do submit a job whether it wants to or not, so the new rocotoboot does do that.  However, there is now a way to easily tell rocotorewind to rewind all final tasks.  One can do two steps to reactivate a drained or completed cycle:

    rocotorewind -w workflow.xml -d workflow.db -c YYYYMMDDHHMM -t :final
    rocotoboot -w workflow.xml -d workflow.db -c YYYYMMDDHHMM -t whatever

The first command rewinds all tasks where the `final` attribute is `true`, and the second boots the task of interest.  In other words, the new rocotoboot gives the user the ability to reactivate cycles without forcing them to do so upon a rocotoboot.  Expired cycles still cannot be reactivated, so rocotoboot and rocotorewind will warn you of that.

A few other important notes about the `-a` (all tasks) option that will address similar issues.

This will mark all tasks as complete, and the cycle as done:

    rocotocomplete -w workflow.xml -d workflow.db -c YYYYMMDDHH -a

This will kill all tasks for the cycle, remove the cycle and its jobs from the database, thus making it as if the cycle has never been started:

    rocotorewind -w workflow.xml -d workflow.db -c YYYYMMDDHH -a

This is madness, and it will tell you so, but it will allow you to do it, and will happily submit all jobs in the cycle:

    rocotoboot -w workflow.xml -d workflow.db -c YYYYMMDDHH -a

You can also give `-c all` to apply an operation to all cycles.  While that is of dubious use for rocotoboot and rocotocomplete, it does have an important use in rocotorewind.  This will kill all jobs and make it as if the workflow was never started:

    rocotorewind -w workflow.xml -d workflow.db -c all -a

It is a more convenient way than doing `qstat ; munge some things ; qdel a bunch of jobids ; rm *.db`

**Comment by samtrahan** [comment]
This was closed by accident.  I have reopened it.

**Comment by samtrahan** [comment]
The rocotostat now accepts the usual -m, -t, -c, and -a options.  However, it appears the -t option in rocotostat was a regex search, rather than a task list like the other options.  In order for users to get the regex search functionality:

    rocotostat -w workflow.xml -d workflow.db ...  -t /regex/

If you just do this, you'll get a task name:

    rocotostat -w workflow.xml -d workflow.db ...  -t task_name

**Comment by samtrahan** [comment]
The rocotocheck is now updated to use the same -a, -t, -m, and -c options as other commands.  All that is left to do is add the `-c @cycledefname` capability.

**Comment by samtrahan** [comment]
This is probably all working, but the beta testers are still reporting occasional problems, surprises that violate the "principle of least surprise," and critical missing features.  I'll want another week or so to test before I consider this ready for a pull request.

**Comment by christopherwharrop** [comment]
This was addressed in pull request #31.  Closing.
