### ISSUE TITLE
rocotostat reports all tasks in every cycle

### ISSUE THREAD

**Issue by ghost** [christopherwharrop/rocoto#2]
When defining multiple **cycledef** in a single **workflow**  there may be some tasks that are not a member of a particular cycle.  Currently **rocotostat** will report on all tasks for every cycle even when it is not member of a cycle in which they will not run.

**Comment by christopherwharrop** [comment]
Thank you for reporting this.  It will be fixed in the next release which should be out in a few weeks.

**Comment by christopherwharrop** [comment]
Terry, Please check out the "issue_2" branch and test to see if it addresses the problem you are seeing.  If so, I will merge it onto the master.

**Comment by christopherwharrop** [comment]
This issue has been fixed and the issue_2 branch is now merged onto the master.  This fix will be included in the 1.2.4 release which should happen within the next few weeks.

**Comment by siva-oceanda** [comment]
Hi Chris,
I am using ROCOTO version 1.3.7. And, I see the same issue of rocotostat reporting all cycles when I invoke
rocotostat -w run.xml.rocoto.SHEMINBLING -d log/workflow/mitdart
Is there a fix for this? Or am I missing something
Best
Siva
