### ISSUE TITLE
rocotorun safety checks

### ISSUE THREAD

**Issue by samtrahan** [christopherwharrop/rocoto#20]
Rocotorun needs to have safety checks specified in the workflow document that Rocoto will run before executing jobs.  These are such things as making sure the quota will not be hit.  The way I was planning on doing this is to implement this:

<workflow ...>
  <dependency>
    <and>
      <not><datadep>/path/to/some/file</datadep></not> 
      <sh>mmlsquotas ... | grep ...</sh> 
      <sh>cat /etc/prod | grep ...</sh> 
    </and>
  </dependency>
  ...
</workflow>

The <dependency> at the <workflow> level would be tested at the top of rocotorun, localized to the time of the first cycle in the document.  Using a cycle is needed to ensure that the <cyclestr> can be evaluated.  This would use the existing <dependency> implementation within Rocoto, which should make the feature easy to add.  Both rocotocheck and rocotorun will be updated.

**Comment by christopherwharrop** [comment]
The above is way too vague.  Please redo to make it a clear description of the specific problem you are reporting and exclude your implementation ideas.  We can discuss the issue and ideas for how to address it in a portable way in the comments that follow.

**Comment by samtrahan** [comment]
Chris,

Somehow github deleted part of my message.  I think it was due to the use of markdown characters in the message.  I'll try again in my next posting.

**Comment by samtrahan** [comment]
Users in my workgroup need the `rocotorun` command to have safety checks specified in the workflow document that Rocoto will run before executing jobs.  These are such things as making sure the quota will not be hit.  The way I was planning on doing this is to implement this:

    <workflow ...>
      <dependency>
        <and>
          <not><datadep>/path/to/some/file</datadep></not> 
          <sh>mmlsquotas ... | grep ...</sh> 
          <sh>cat /etc/prod | grep ...</sh> 
        </and>
      </dependency>
      ...
    </workflow>

The `<dependency>` at the `<workflow>` level would be tested at the top of `rocotorun`, localized to the time of the first cycle in the document.  Using a cycle is needed to ensure that the `<cyclestr>` can be evaluated.  This would use the existing `<dependency>` implementation within Rocoto, which should make the feature easy to add.  Both `rocotocheck` and `rocotorun` will be updated.

**Comment by samtrahan** [comment]
I got it right on the third try.  I totally forgot that github supports markdown.
