### ISSUE TITLE
Rocoto does not scrub the ~/.rocoto/ files

### ISSUE THREAD

**Issue by samtrahan** [christopherwharrop/rocoto#27]
Users have reported problems of Rocoto making numerous files in the `~/.rocoto/` directories.  These have been traced down to bugs before and fixed.  However, bugs will happen again (they always do).  Adding the pid directory for the NOBatchSystem will make this worse.  I propose adding a simple scrubber function called from the workflow engine every time a Rocoto program starts.  It would:

1. Delete all files older than 20 days except the few we know we need to keep.
2. Delete any pid files from NOBatchSystem older than 5 days.

This would be configurable.

**Comment by christopherwharrop** [comment]
This should be addressed in PR #51
