### ISSUE TITLE
Rocoto "job.duration" in workflowengine.rb returns "no implicit conversion to float from nil" error

### ISSUE THREAD

**Issue by rajancr** [christopherwharrop/rocoto#3]
Hello,

The “job.duration=status[:end_time] - status[:start_time]” returns "no implicit conversion to float from nil"

file: rocoto/lib/workflowmgr/workflowengine.rb
line#: 1043

Further I made a fix to the "status" variable with explicitly specifying the data type as int / float 
ie. 
job.duration=status[:end_time].to_i - status[:start_time].to_i
job.duration=status[:end_time].to_f - status[:start_time].to_f

this resolved the specified error, however both of them failed to return the job execution time in seconds rather it returns 0.0 (for float) or 0 (for integer)

The current environment is as follows:
Operating System - RedHat 7.2
Rocoto - 1.2.3
Ruby - 1.8.7
Job Scheduler - LSF

Please provide the appropriate resolution.

Regards
-Rajan

**Comment by christopherwharrop** [comment]
Sorry for the late response.  I've been on travel for the past 10 days.  Thank you for reporting this bug and providing detailed information.  I will take a look and get a fix ASAP.

**Comment by christopherwharrop** [comment]
What version of LSF are you using?  I have had trouble in the past when LSF changed the output and caused the completion time information to not get parsed correctly.  I suspect that is what is happening here too.  What would be helpful is if you could provide some output of `bjobs -l -a` and `bhist -l -d -w` so that I can see the formatting and check if there is a discrepancy.  Also, sometimes, the format of the output is different for jobs that succeed vs ones that fail.  If you could send output for both, that would help me.

**Comment by rajancr** [comment]
IBM Platform LSF Standard 9.1.3.0, Jul 04 2014

Here is the bjobs -l -a output 

$ bjobs -l -a

Job <112573>, Job Name <he>, User <rravindran>, Project <default>, Status <RUN>
                     , Queue <q2697v4edr2400all>, Command <#!/bin/bash; #BSUB -
                     q q2697v4edr2400all ;#BSUB -n 256 ;#BSUB -W 1:30;#BSUB -x;
                     #BSUB -J he ;#BSUB -o he.stdout.%J;#BSUB -e he.stderr.%J;#
                     BSUB -R "select[hname!=nxt0228]";#BSUB -R "select[hname!=n
                     xt0326]";#BSUB -R "span[ptile=28]"; MPI=256;PPN=28;MYDIR=$
                     (pwd); EXE=/home/rravindran/test/hello/hello;  #FREQ=26000
                     00                                   # [kHz], turbo mode i
                     s default if set_freq_lsf.sh not used;#/home/lsfadmin/bin/
                     set_freq_lsf.sh -p $FREQ    # optional -p flag uses perfor
                     mance governor instead userspace; module load compiler/int
                     el/15.0.2;module load mpi/intel/5.0.3;#module add mpi/inte
                     l/5.0.3  compiler/intel/15.0.2; # DAPL;export I_MPI_FABRIC
                     S=shm:dapl;#export I_MPI_DAPL_UD=enable;export I_MPI_FALLB
                     ACK=0; export I_MPI_DEBUG=6; #export I_MPI_PIN_PROCESSOR_L
                     IST=0-27;  rm -f host.list ;cat $LSB_DJOB_HOSTFILE > ./hos
                     t.list ; env > log.env; { time mpiexec.hydra -np $MPI -f .
                     /host.list -genvall -ppn $PPN  $EXE ; } > $MYDIR/hello.out
                       2>&1>
Mon Nov  7 17:00:41: Submitted from host <login0401>, CWD <$HOME/test/hello>, O
                     utput File <he.stdout.112573>, Error File <he.stderr.11257
                     3>, Exclusive Execution, 256 Task(s), Requested Resources
                     < select[(hname!=nxt0228)&&(hname!=nxt0326)] span[ptile=28
                     ]>;

 RUNLIMIT
 90.0 min of nxt0226
Mon Nov  7 17:00:41: Started 256 Task(s) on Host(s) <28*nxt0226> <28*nxt0224> <
                     28_nxt0218> <28_nxt0221> <28*nxt0225> <28*nxt0220> <28*nxt
                     0216> <28*nxt0215> <28*nxt0217> <4*nxt0223>, Allocated 720
                      Slot(s) on Host(s) <72*nxt0226> <72*nxt0224> <72*nxt0218>
                     <72*nxt0221> <72*nxt0225> <72*nxt0220> <72*nxt0216> <72*nx
                     t0215> <72*nxt0217> <72*nxt0223>;

 SCHEDULING PARAMETERS:
           r15s   r1m  r15m   ut      pg    io   ls    it    tmp    swp    mem
 loadSched   -     -     -     -       -     -    -     -     -      -      -
 loadStop    -     -     -     -       -     -    -     -     -      -      -

 RESOURCE REQUIREMENT DETAILS:
 Combined: select[((hname != nxt0228 )&&(hname != nxt0326 )) && (type == any)]
                     order[r15s:pg] span[ptile=28] cu[pref=config:maxcus=10:typ
                     e=leaf]
 Effective: select[(((hname != nxt0228 )&&(hname != nxt0326 )) && (type == any)
                     )] order[r15s:pg] span[ptile=28] cu[type=leaf:maxcus=10:pr
                     ef=config]

**Comment by christopherwharrop** [comment]
Thank you!  That certainly helps.  I believe there is indeed a mismatch in the format that LSF is sending and what Rocoto is expecting.  LSF is notoriously difficult to deal with compared to other batch systems in this regard.  Can you supply output for "bjobs -l -a" that includes the completion notification?  The one you included only has the submission and start times.  If I can see the completion (both successful and failures) that will give me the full picture.  

I will have a branch for you to test soon.

**Comment by rajancr** [comment]
Here is the output post the completion

$ bjobs -l -a

Job <112573>, Job Name <he>, User <rravindran>, Project <default>, Status <DONE
                     >, Queue <q2697v4edr2400all>, Command <#!/bin/bash; #BSUB
                     -q q2697v4edr2400all ;#BSUB -n 256 ;#BSUB -W 1:30;#BSUB -x
                     ;#BSUB -J he ;#BSUB -o he.stdout.%J;#BSUB -e he.stderr.%J;
                     #BSUB -R "select[hname!=nxt0228]";#BSUB -R "select[hname!=
                     nxt0326]";#BSUB -R "span[ptile=28]"; MPI=256;PPN=28;MYDIR=
                     $(pwd); EXE=/home/rravindran/test/hello/hello;  #FREQ=2600
                     000                                   # [kHz], turbo mode
                     is default if set_freq_lsf.sh not used;#/home/lsfadmin/bin
                     /set_freq_lsf.sh -p $FREQ    # optional -p flag uses perfo
                     rmance governor instead userspace; module load compiler/in
                     tel/15.0.2;module load mpi/intel/5.0.3;#module add mpi/int
                     el/5.0.3  compiler/intel/15.0.2; # DAPL;export I_MPI_FABRI
                     CS=shm:dapl;#export I_MPI_DAPL_UD=enable;export I_MPI_FALL
                     BACK=0; export I_MPI_DEBUG=6; #export I_MPI_PIN_PROCESSOR_
                     LIST=0-27;  rm -f host.list ;cat $LSB_DJOB_HOSTFILE > ./ho
                     st.list ; env > log.env; { time mpiexec.hydra -np $MPI -f
                     ./host.list -genvall -ppn $PPN  $EXE ; } > $MYDIR/hello.ou
                     t  2>&1>
Mon Nov  7 17:00:41: Submitted from host <login0401>, CWD <$HOME/test/hello>, O
                     utput File <he.stdout.112573>, Error File <he.stderr.11257
                     3>, Exclusive Execution, 256 Task(s), Requested Resources
                     < select[(hname!=nxt0228)&&(hname!=nxt0326)] span[ptile=28
                     ]>;

 RUNLIMIT
 90.0 min of nxt0226
Mon Nov  7 17:00:41: Started 256 Task(s) on Host(s) <28*nxt0226> <28*nxt0224> <
                     28_nxt0218> <28_nxt0221> <28*nxt0225> <28*nxt0220> <28*nxt
                     0216> <28*nxt0215> <28*nxt0217> <4*nxt0223>, Allocated 720
                      Slot(s) on Host(s) <72*nxt0226> <72*nxt0224> <72*nxt0218>
                     <72*nxt0221> <72*nxt0225> <72*nxt0220> <72*nxt0216> <72*nx
                     t0215> <72*nxt0217> <72*nxt0223>, Execution Home </home/rr
                     avindran>, Execution CWD </home/rravindran/test/hello>;
Mon Nov  7 17:01:52: Done successfully. The CPU time used is 7.0 seconds.

 MEMORY USAGE:
 MAX MEM: 132 Mbytes;  AVG MEM: 105 Mbytes

 SCHEDULING PARAMETERS:
           r15s   r1m  r15m   ut      pg    io   ls    it    tmp    swp    mem
 loadSched   -     -     -     -       -     -    -     -     -      -      -
 loadStop    -     -     -     -       -     -    -     -     -      -      -

 RESOURCE REQUIREMENT DETAILS:
 Combined: select[((hname != nxt0228 )&&(hname != nxt0326 )) && (type == any)]
                     order[r15s:pg] span[ptile=28] cu[pref=config:maxcus=10:typ
                     e=leaf]
 Effective: select[(((hname != nxt0228 )&&(hname != nxt0326 )) && (type == any)
                     )] order[r15s:pg] span[ptile=28] cu[type=leaf:maxcus=10:pr
                     ef=config]

**Comment by christopherwharrop** [comment]
I have made some updates that should help.  Please obtain a fresh clone and then do "git checkout issue_3".  Then run ./INSTALL and test to see if there is any improvement.

**Comment by christopherwharrop** [comment]
I will be releasing a new version very soon.  Have you had a chance to test the update?  Please test ASAP and let me know the result.

**Comment by christopherwharrop** [comment]
rajancr, the release of version 1.2.3 is imminent.  If you want this fix included, I need feedback from you on whether this patch works in the next 24-48 hours.  Since I can't reproduce the issue, I must rely on you to test it.

**Comment by christopherwharrop** [comment]
This issue is being closed due to lack of response from the user and our inability to reproduce the problem.  If the problem still exists in version 1.2.3 and the user is willing to work with us to debug and test proposed patches, please fee free to reopen.
