### ISSUE TITLE
SLURM jobs "UNAVAILABLE" around midnight

### ISSUE THREAD

**Issue by samtrahan** [christopherwharrop/rocoto#38]
On SLURM, some jobs were ending up in `UNAVAILABLE` status because:

1. The job disappeared from scontrol before rocotorun was run, and
2. The sacct command, by default, only prints history since midnight system time.

Thus, any jobs that finish a little bit before midnight, that scontrol does not report to rocotorun, will never be seen by Rocoto.

The fix:

1. The first time sacct is run, it is requested to search back one full day of history, and
2. If the job still is not found, then it will search back several days.

This is fixed in branch `feature/sacct-multi-day`

**Comment by christopherwharrop** [comment]
Thank you for finding and diagnosing this.  Thanks also for the fix.

In the future, please use a "bugfix" branch when addressing bug fixes.

E.g. bugfix/sacct-multi-day

That way bug fix branches are easily distinguishable from branches that are adding new features.

**Comment by samtrahan** [comment]
The branch has been renamed.

**Comment by samtrahan** [comment]
The branch is merged into release/1.3.0.  I'm considering this issue resolved, as that branch will be merged into develop and master eventually.
