### ISSUE TITLE
SLURM exporting all variables instead of selected ones

### ISSUE THREAD

**Issue by samtrahan** [christopherwharrop/rocoto#39]
In SLURM, by default, all environment variables are exported to the job, leading to a variety of confusing errors.  The change in branch `bugfix/slurm-no-default-export` uses `--export=NONE` to disable default exporting.  That way, only the ones in `<envar>` blocks are exported.

This fix is being tested now.  We hope to have test results by the end of the day.

**Comment by christopherwharrop** [comment]
Thank you for finding and diagnosing this, and for testing a fix.  A quick reminder: bug fixes should be done in "bugfix" branches, not "feature" branches.

**Comment by samtrahan** [comment]
The branch has been renamed.

**Comment by samtrahan** [comment]
Terry has reported back that the fix worked, so I'm going to do a pull request for this shortly...

**Comment by christopherwharrop** [comment]
This was fixed in PR #41 .  Closing.
