### ISSUE TITLE
When run for the first time, rocoto submits the first job infinitely

### ISSUE THREAD

**Issue by samtrahan** [christopherwharrop/rocoto#4]
Problem: when a user runs Rocoto for the first time, Rocoto resubmits the first job infinitely.

Cause: Log rotation logic did not check if a log file ~/.rocoto/log existed before checking its age.  This caused the rocoto batch queue server to abort without reporting on the success or failure of job submission. Rocoto then diligently resubmitted the job, ad infinum.

Solution: Only rotate the logs if there are logs to rotate.

**Comment by samtrahan** [comment]
Addendum:  the behaviour of the bug depends on where you run Rocoto. 

WCOSS Gyre: the "log" logfile is never created, and Rocoto cannot detect job submissions.  Jobs are submitted infinitely.

RDHPCS Theia: the "log" logfile is never created.  Rocoto works correctly otherwise.

**Comment by christopherwharrop** [comment]
The pull request addressing this issue has been merged.  Closing.
