### ISSUE TITLE
Rocoto uses more than 64 byte limit to squeue --jobs

### ISSUE THREAD

**Issue by samtrahan** [christopherwharrop/rocoto#58]
The squeue --jobs option has a limit of 64 characters, but Rocoto does not check that limit before calling squeue.  A fix for this is in the bugfix/smallj branch.

**Comment by christopherwharrop** [comment]
Did you try using SLURM_BITSTR_LEN to fix it?  64 bytes is ridiculously small.  I'd like to keep the --jobs option for at least couple dozen jobs.  And we're no where near the unix command length limit.  Is there an internal command line buffer limit inside of Slurm?  64 BYTES?!? what were they thinking?!

**Comment by samtrahan** [comment]
The documentation might be lying:

squeue -j 161297,160861,166796,166712,166559,166473,165715,165595,165592,165449,165346,163591,163304,163309,163312,162129,162121,162120,161688,161529 -t all -M all -a

That works despite the documentation's claims.  Setting the variable seems to have no effect whatsoever:

/usr/bin/env SLURM_BITSTR_LEN=33 squeue -j 161297,160861,166796,166712,166559,166473,165715,165595,165592,165449,165346,163591,163304,163309,163312,162129,162121,162120,161688,161529 -t all -M all -a

That should cause an abort, but it doesn't.

**Comment by christopherwharrop** [comment]
Have they set SLURM_BITSTR_LEN to a large number in the Slurm configuration?

**Comment by samtrahan** [comment]
I did a recursive search of the slurm installation directory on NOAA Jet of all files, including binary files, for the string SLURM_BITSTR_LEN (caselessly) and only found it in the documentation.

**Comment by christopherwharrop** [comment]
Well, that wouldn't be the first time I've run across lying documentation...  Oh well.  Because this has some significant performance impacts (a single role account user could have THOUSANDS of jobs), I'd like a definitive answer from SchedMD on how this works.

**Comment by christopherwharrop** [comment]
This is resolved with PR #62
