### ISSUE TITLE
Allow Rocoto to report status of read-only workflows

### ISSUE THREAD

**Issue by samtrahan** [christopherwharrop/rocoto#6]
When another user is running Rocoto and requests help, others need to be able to check the Rocoto workflow without write access.  That means rocotostat and rocotocheck need to be able to run on a read-only database.  However, any change must ensure that write-requiring commands fail gracefully.

**Comment by samtrahan** [comment]
The "readonly" branch contains code to support this.  Gist of the changes:

1. If the two *.db files exist and are unwritable, then Rocoto drops to read-only mode.  This is reported via the new readonly? function.

2. Commands like rocotorun and rocotoboot call a new disallow_readonly function which aborts with a message in read-only mode.

3. The workflowdb disables locking in read-only mode, and won't even open the lock db.

4. All other functions in workflowdb that require writing are disabled in read-only mode.

5. In read-only mode, the main workflow db is opened with the sqlite3 `:readonly` option.  This causes sqlite3 to open the file read-only and forbid any commands that require writing.

**Comment by samtrahan** [comment]
I am reclassifying this as a bug, because Rocoto 1.2.3 lost critical functionality that Rocoto 1.2.2 had.  In Rocoto 1.2.2, you could view another user's workflow.  With Rocoto 1.2.3, that functionality is lost.

**Comment by samtrahan** [comment]
Bug fix is in `readonly` branch, awaiting pull to master.

**Comment by christopherwharrop** [comment]
An alternative solution to this problem was implemented and tested in the issue_6 branch.  That branch has been merged onto the master and then deleted.  This issue is closed.
