### ISSUE TITLE
sourcing /etc/profile causes various problems on WCOSS Crays

### ISSUE THREAD

**Issue by samtrahan** [christopherwharrop/rocoto#8]
This line can be found in the various bin/ scripts:

     . /etc/profile

On the WCOSS Crays, if /etc/profile has already been sourced, then sourcing it again can cause several problems.  Known problems thus far:

- the `/etc/profile` reloads the module command incorrectly
- this sources the user's bashrc a second time, causing modules to be loaded again.  Generally, that does not work on the WCOSS Crays
- the `$*` variable is clobbered, causing the ruby scripts to receive no arguments, or the wrong arguments

**Comment by samtrahan** [comment]
Workaround is in issue_8 branch, but should be further tested before pulling to master.  The workaround is to:

1. Store `$*` in `$rocoto__args`
2. Only source `/etc/profile` if the `module` command is missing or broken
3. Restore `$*` from `$rocoto__args`

The implausible `$rocoto__args` variable (note the double underscore) is chosen because no sane person would use it in an ordinary shell script.

**Comment by christopherwharrop** [comment]
I wonder if "shopt -q login_shell" can assist with this.  I'm taking a look.

**Comment by christopherwharrop** [comment]
shopt -q does work to determine if a shell is a login shell or not, but it's actually pretty useless since you can't change the login_shell attribute after a shell is created.

**Comment by christopherwharrop** [comment]
The issue_8 branch has been merged onto the master.  Extensive testing on Theia and Cheyenne show no issues.
