### ISSUE TITLE
double quotes in <native> blocks insert &;quot;

### ISSUE THREAD

**Issue by samtrahan** [christopherwharrop/rocoto#9]
If Rocoto sees a double quote in a <native> tag, it inserts &;quot; in the "bsub" command to the LSF batch system.  The workaround so far has been to use single quotes.

**Comment by samtrahan** [comment]
Fix is in issue_9 branch.  There were two problems:

1. There was a missing `;` in the code that handled replacement of `&amp;`

2. There were some missing calls to `unescape()` in workflowdoc.rb.  This caused some tags to retain their XML entities.

**Comment by christopherwharrop** [comment]
The pull request to merge the issue_9 branch has been performed.  The issue_9 branch has been removed.  This issue is closed.
