### ISSUE TITLE
Rocotostat shows Task state "Queued" even after task completed

### ISSUE THREAD

**Issue by anitathite** [christopherwharrop/rocoto#92]
Hello Sir,

I am running 4 step job (Each step has 40 tasks) with rocotorun command. 
First step always completes successfully but still second step's tasks are never submitted. 
Rocotostat shows Task state "Queued" even after first tasks completed by PBS scheduler.
Do I need to set any configuration in PBSPRO scheduler?
Please help. 
Attaching here rocotostat snapshot.
![Rocotostat_run](https://user-images.githubusercontent.com/35448433/123542778-278caa00-d769-11eb-878e-33569ef08dc4.jpeg)

**Comment by christopherwharrop-noaa** [comment]
@anitathite - When you encountered this problem did you first run `rocotorun` to ensure that the state of the workflow was up to date?  Rocoto works in an iterative fashion. When you run the `rocotostat` command, it only knows about the last known state of the workflow.  To update the state,  you must run `rocotorun`.  Each time you run `rocotorun` it reads the last known state, updates the current state of the workflow, submits new jobs if dependencies have been satisfied.  `rocotostat` only knows about the state corresponding to the last time you ran `rocotorun`.  So, if you did not run `rocotorun` again, that is why it would still say it is queued.
